Repository resumeme/Backend, pull requests merged in 2023-10, with the labels that each got.

#1 [GMMQ-8] feat: CICD Workflow 템플릿 생성입니다
  .github/workflows/Deploy.yml
  .github/workflows/PR_Test.yml
Labels: FEAT

#2 [GMMQ-8] feat: codeDeploy 설정 파일 추가
  appspec.yml
  scripts/deploy.sh
Labels: FEAT

#6 [GMMQ-27] feat: RestDocs 추가 설정
  build.gradle
  src/docs/asciidoc/docinfo.html
  src/docs/asciidoc/index.adoc
  src/main/java/org/devcourse/resumeme/common/domain/DocsEnumType.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/resources/org/springframework/restdocs/templates/enum-response-fields.snippet
Labels: FEAT

#13 feat: 이력서 첨삭 이벤트 도메인 추출
  src/main/java/org/devcourse/resumeme/common/domain/Position.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventStatus.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
Labels: FEAT

#14 feat: Resume 도메인 클래스 추가
  src/main/java/org/devcourse/resumeme/common/domain/Position.java
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/domain/resume/Training.java
Labels: FEAT

#17 docs: Github Action WorkFlow 수정
  .github/workflows/Deploy.yml
  .github/workflows/PR_Test.yml
Labels: FEAT

#19 feat: Security Endpoint yml 파일 분리
  build.gradle
  src/main/java/org/devcourse/resumeme/global/config/EndpointProperties.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/WebConfig.java
  src/main/resources/application-endpoint.yml
  src/main/resources/application.yml
  src/test/java/org/devcourse/resumeme/ResumemeApplicationTests.java
Labels: FEAT

#22 fix: dev환경 MySQL 의존성 추가 및 CD step 순서 변경
  .github/workflows/Deploy.yml
  build.gradle
Labels: FEAT

#26 feat: 이력서 등록 기능 구현
  src/main/java/org/devcourse/resumeme/common/util/Validator.java
  src/main/java/org/devcourse/resumeme/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ResumeCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/metor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/CustomException.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/repository/ResumeRepository.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
  src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
Labels: FEAT

#27 fix: endpoint 설정 http method 추가
  src/main/java/org/devcourse/resumeme/global/config/EndpointProperties.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/resources/application-endpoint.yml
Labels: HotFix

#24 feat: 사용자는 카카오 로그인을 사용하여 가입을 할 수 있다
  src/main/java/org/devcourse/resumeme/controller/UserController.java
  src/main/java/org/devcourse/resumeme/controller/dto/PrimarySignUpInfo.java
  src/main/java/org/devcourse/resumeme/domain/user/Provider.java
  src/main/java/org/devcourse/resumeme/domain/user/Role.java
  src/main/java/org/devcourse/resumeme/domain/user/User.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/GoogleOAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/repository/UserRepository.java
  src/main/java/org/devcourse/resumeme/service/UserService.java
  src/main/resources/application.yml
Labels: FEAT

#29 fix: 오타 수정
  .github/workflows/Deploy.yml
Labels: HotFix

#28 feat: 이벤트 생성 API 생성입니다
  src/main/java/org/devcourse/resumeme/common/response/IdResponse.java
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/dto/EventCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/common/util/ApiDocumentUtils.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
Labels: FEAT

#31 fix: 경로 수정
  .github/workflows/Deploy.yml
  scripts/properties.sh
Labels: HotFix

#30 docs: Enum Code 관련 문서화 처리입니다
  .gitignore
  src/docs/asciidoc/common/eventStatus.adoc
  src/docs/asciidoc/common/position.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/org/devcourse/resumeme/common/domain/Position.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
Labels: Documentation

#34 feat: Event 생성 request 필드 추가
  src/main/java/org/devcourse/resumeme/controller/dto/EventCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTimeInfoTest.java
  src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
Labels: Feat

#35 feat: 소셜로그인 yml 설정
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/resources/application-auth.yml
  src/main/resources/application.yml
Labels: Feat

#41 feat: 경력 사항 등록 기능 구현
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/Duty.java
  src/main/java/org/devcourse/resumeme/domain/resume/EmploymentType.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/domain/resume/Skill.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: Feat

#42 feat: 첨삭 이벤트 참여 기능 구현입니다
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ApplyToEventRequest.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/main/java/org/devcourse/resumeme/service/vo/AcceptMenteeToEvent.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
  src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
  src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
Labels: Feat

#43 feat: 프로젝트 등록 기능 구현
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/test/java/org/devcourse/resumeme/domain/resume/ProjectTest.java
Labels: Feat

#45 fix: properties 경로 절대경로로 변경
  scripts/deploy.sh
Labels: HotFix

#44 feat: 이벤트 신청 도메인 필드 수정
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/domain/event/Progress.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
Labels: Feat

#47 feat: 멘토의 멘티 신청 반려 기능 구현
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/dto/EventRejectRequest.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/main/java/org/devcourse/resumeme/service/vo/EventReject.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
  src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
Labels: Feat

#48 feat: 수상 및 자격 등록 기능 추가
  src/main/java/org/devcourse/resumeme/domain/resume/Certification.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/test/java/org/devcourse/resumeme/domain/resume/CertificationTest.java
Labels: Feat

#49 feat: 활동, 외국어 아이템 추가
  src/main/java/org/devcourse/resumeme/domain/resume/Activity.java
  src/main/java/org/devcourse/resumeme/domain/resume/Certification.java
  src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/test/java/org/devcourse/resumeme/domain/resume/ActivityTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java
Labels: Feat

#46 feat: 소셜 회원가입 이력이 없는 사용자는 필수 추가정보 입력해야한다.
  build.gradle
  src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/user/Provider.java
  src/main/java/org/devcourse/resumeme/domain/user/UserCommonInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2FailureHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/model/Claims.java
  src/main/java/org/devcourse/resumeme/global/auth/model/OAuth2TempInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/GoogleOAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java
  src/main/java/org/devcourse/resumeme/global/config/RedisRepositoryConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/repository/MenteeRepository.java
  src/main/java/org/devcourse/resumeme/repository/MentorRepository.java
  src/main/java/org/devcourse/resumeme/repository/OAuth2TempInfoRepository.java
  src/main/java/org/devcourse/resumeme/service/MenteeService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: Feat

#50 feat: 로그인 필터 구현
  src/main/java/org/devcourse/resumeme/global/auth/OAuthTokenResponseFilter.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
  src/main/resources/application-endpoint.yml
Labels: Feat

#51 feat: 이력서 저장 기능 구현
  src/main/java/org/devcourse/resumeme/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ResumeCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/ResumeTest.java
Labels: Feat

#53 feat: 이벤트 중복 생성 금지 로직 추가
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/EventStatus.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
Labels: Feat

#54 feat: 이력서저장 index.html 추가
  src/docs/asciidoc/index.adoc
Labels: Feat

#55 fix: api docs jar 미포함 문제 수정 및 docs 작성
  .github/workflows/Deploy.yml
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/resources/application-endpoint.yml
Labels: HotFix

#52 feat: jwt 토큰 검증
  src/main/java/org/devcourse/resumeme/controller/MenteeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/RegisterInfoRequest.java
  src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/user/Role.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/model/JwtUser.java
  src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
  src/main/java/org/devcourse/resumeme/repository/OAuth2InfoRedisRepository.java
Labels: Feat

#56 feat: 이벤트 신청 시 이력서 복사
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/support/WithMockCustomUser.java
  src/test/java/org/devcourse/resumeme/support/WithMockCustomUserSecurityContextFactory.java
Labels: Feat

#57 feat: 이벤트 리뷰 도메인 도출
  src/main/java/org/devcourse/resumeme/domain/resume/BlockType.java
  src/main/java/org/devcourse/resumeme/domain/review/Review.java
  src/main/java/org/devcourse/resumeme/repository/ReviewRepository.java
  src/test/java/org/devcourse/resumeme/domain/review/ReviewTest.java
Labels: Feat

#58 feat: 리뷰 생성 관련 api 생성
  src/docs/asciidoc/index.adoc
  src/main/java/org/devcourse/resumeme/controller/ReviewController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ReviewCreateRequest.java
  src/main/java/org/devcourse/resumeme/controller/dto/ReviewResponse.java
  src/main/java/org/devcourse/resumeme/domain/review/Review.java
  src/main/java/org/devcourse/resumeme/service/ReviewService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
Labels: Feat

#59 feat: 이력서 block 연관관계 수정
  src/main/java/org/devcourse/resumeme/domain/resume/Activity.java
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/Certification.java
  src/main/java/org/devcourse/resumeme/domain/resume/Duty.java
  src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: Feat

#60 feat: 리뷰 재요청 기능 구현
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/domain/event/Progress.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
Labels: Feat

#63 feat: 멘토 도메인 검증로직 추가 및 테스트 코드 작성
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
Labels: Feat

#64 feat: 첨삭 전 후 이력서 멘토 조회
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/dto/EventResponse.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
Labels: Feat

#65 docs: 문서 role 별로 분리
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
Labels: Documentation

#67 feat: 업무경험 저장 api 구현
  src/main/java/org/devcourse/resumeme/controller/CareerController.java
  src/main/java/org/devcourse/resumeme/controller/dto/CareerCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/repository/CareerRepository.java
  src/main/java/org/devcourse/resumeme/service/CareerService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: Feat

#66 feat: 어드민 도메인 구현
  src/main/java/org/devcourse/resumeme/domain/admin/Admin.java
  src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java
  src/main/java/org/devcourse/resumeme/domain/admin/MentorApplicationEvent.java
  src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationEventListener.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
Labels: Feat

#72 feat: 어드민 멘토 승인 요청 조회, 승인처리 기능 구현
  src/main/java/org/devcourse/resumeme/controller/MentorApplicationController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ApplicationProcessType.java
  src/main/java/org/devcourse/resumeme/controller/dto/MentorApplicationResponse.java
  src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
  src/main/java/org/devcourse/resumeme/service/MentorService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java
Labels: Feat

#73 fix: 네이밍 변경
  src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
Labels: HotFix

#76 feat: 합격 이력서 소개글 작성
  src/main/java/org/devcourse/resumeme/controller/ResultNoticeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/CreateResultRequest.java
  src/main/java/org/devcourse/resumeme/domain/result/ResultNotice.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/repository/ResultNoticeRepository.java
  src/main/java/org/devcourse/resumeme/service/ResultService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
Labels: Feat

#75 feat: 멘티는 개인정보를 수정할 수 있다
  src/main/java/org/devcourse/resumeme/controller/MenteeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/MenteeInfoUpdateRequest.java
  src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/service/MenteeService.java
  src/main/resources/application-endpoint.yml
Labels: Feat

#78 feat: 활동 및 외국어 저장 기능 구현
  src/main/java/org/devcourse/resumeme/controller/ActivityController.java
  src/main/java/org/devcourse/resumeme/controller/ForeignLanguageController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ActivityRequestDto.java
  src/main/java/org/devcourse/resumeme/controller/dto/ForeignLanguageRequestDto.java
  src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/repository/ActivityRepository.java
  src/main/java/org/devcourse/resumeme/repository/ForeignLanguageRepository.java
  src/main/java/org/devcourse/resumeme/service/ActivityService.java
  src/main/java/org/devcourse/resumeme/service/ForeignLanguageService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java
Labels: Feat

#74 feat: endpoint 동적 권한 처리 기능 구현
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/ReviewController.java
  src/main/java/org/devcourse/resumeme/global/config/EndpointProperties.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/authorization/AuthorizationResolver.java
  src/main/java/org/devcourse/resumeme/global/config/authorization/OnlyOwn.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/repository/ResumeRepository.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
Labels: Feat

#77 fix: OAuth2TempInfo id값 할당 및 회원가입 후 삭제 로직 추가
  src/main/java/org/devcourse/resumeme/controller/MenteeController.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/model/OAuth2TempInfo.java
  src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java
  src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
Labels: Feat

#79 feat: 합격 이력서 페이징 조회
  src/main/java/org/devcourse/resumeme/controller/ResultNoticeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ResultsResponse.java
  src/main/java/org/devcourse/resumeme/domain/result/ResultNotice.java
  src/main/java/org/devcourse/resumeme/repository/ResultNoticeRepository.java
  src/main/java/org/devcourse/resumeme/service/ResultService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
Labels: Feat

#80 feat: 교육사항 저장 기능 구현
  src/main/java/org/devcourse/resumeme/controller/TrainingController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ProjectCreateRequest.java
  src/main/java/org/devcourse/resumeme/controller/dto/TrainingCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/resume/Training.java
  src/main/java/org/devcourse/resumeme/repository/TrainingRepository.java
  src/main/java/org/devcourse/resumeme/service/TrainingService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/TrainingControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/TrainingTest.java
Labels: Feat
