Repository resumeme/Backend, pull requests merged in 2023-11, with the labels that each got.

#81 feat: 이벤트 전체 조회 api 구현
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/main/java/org/devcourse/resumeme/controller/dto/EventsResponse.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java
  src/main/java/org/devcourse/resumeme/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
Labels: Feat

#83 docs: 이력서 저장 index.html 추가
  src/docs/asciidoc/all.adoc
Labels: Feat

#84 feat: 이벤트 단건 조회 역할 별 반환 값 분리
  src/main/java/org/devcourse/resumeme/controller/EventController.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/support/WithMockCustomUser.java
  src/test/java/org/devcourse/resumeme/support/WithMockCustomUserSecurityContextFactory.java
Labels: Feat

#86 chore: validator 메소드명 수정
  src/main/java/org/devcourse/resumeme/common/util/Validator.java
  src/main/java/org/devcourse/resumeme/domain/admin/Admin.java
  src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java
  src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/domain/mentee/MenteeField.java
  src/main/java/org/devcourse/resumeme/domain/mentee/MenteePosition.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/mentor/MentorPosition.java
  src/main/java/org/devcourse/resumeme/domain/resume/Activity.java
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/Certification.java
  src/main/java/org/devcourse/resumeme/domain/resume/Duty.java
  src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/domain/resume/Training.java
  src/main/java/org/devcourse/resumeme/domain/review/Review.java
Labels: Chore

#87 chore: package 구조 변경
  src/main/java/org/devcourse/resumeme/global/auth/authorization/AuthorizationResolver.java
  src/main/java/org/devcourse/resumeme/global/auth/authorization/OnlyOwn.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2FailureHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2SuccessHandler.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
  src/main/java/org/devcourse/resumeme/global/config/properties/EndpointProperties.java
Labels: Chore

#85 feat: 이력서에 작성된 리뷰 전체 조회
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/common/blockType.adoc
  src/docs/asciidoc/common/progress.adoc
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/controller/ReviewController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ReviewResponse.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/resume/BlockType.java
  src/main/java/org/devcourse/resumeme/repository/ReviewRepository.java
  src/main/java/org/devcourse/resumeme/service/ReviewService.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
Labels: Feat

#88 feat: 업무경험 조회 api 구현
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/resume.adoc
  src/main/java/org/devcourse/resumeme/controller/CareerController.java
  src/main/java/org/devcourse/resumeme/controller/dto/CareerCreateRequest.java
  src/main/java/org/devcourse/resumeme/controller/dto/CareerResponse.java
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java
  src/main/java/org/devcourse/resumeme/domain/resume/Duty.java
  src/main/java/org/devcourse/resumeme/service/CareerService.java
  src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: Feat

#89 feat: 멘티 도메인 검증로직 추가 및 테스트코드 작성
  src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/TrainingControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java
  src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
  src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
  src/test/java/org/devcourse/resumeme/domain/mentee/MenteeTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/ProjectTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/TrainingTest.java
  src/test/java/org/devcourse/resumeme/domain/review/ReviewTest.java
  src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
Labels: Feat

#90 refactor: OAuthTokenResponseFilter 리팩토링
  src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthAuthenticationToken.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenProvider.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenResolver.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
Labels: Refactor

#92 feat: 프론트로부터 받은 code -> token받아오기 필터 테스트
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/common/provider.adoc
  src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/AuthFilterTestController.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
Labels: Feat

#91 docs: 이력서 table 추가
  src/docs/asciidoc/resume.adoc
Labels: Documentation

#94 feat: 멘토,멘티 조회 및 수정 로직 구현
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/common/role.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/docs/asciidoc/resume.adoc
  src/main/java/org/devcourse/resumeme/controller/MenteeController.java
  src/main/java/org/devcourse/resumeme/controller/MentorController.java
  src/main/java/org/devcourse/resumeme/controller/dto/MenteeInfoResponse.java
  src/main/java/org/devcourse/resumeme/controller/dto/MentorInfoResponse.java
  src/main/java/org/devcourse/resumeme/controller/dto/MentorInfoUpdateRequest.java
  src/main/java/org/devcourse/resumeme/domain/mentee/MenteeField.java
  src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/domain/mentor/MentorPosition.java
  src/main/java/org/devcourse/resumeme/service/MenteeService.java
  src/main/java/org/devcourse/resumeme/service/MentorService.java
  src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
Labels: Feat

#93 refactor: exception code로 변환
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/reference.adoc
  src/main/java/org/devcourse/resumeme/common/util/Validator.java
  src/main/java/org/devcourse/resumeme/domain/event/Event.java
  src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java
  src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java
  src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/domain/event/exception/EventException.java
  src/main/java/org/devcourse/resumeme/domain/review/Review.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/service/EventService.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationEventPublisher.java
  src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
  src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java
  src/test/java/org/devcourse/resumeme/common/controller/EnumController.java
  src/test/java/org/devcourse/resumeme/domain/mentee/MenteeTest.java
  src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
Labels: Refactor

#95 feat: controller advice 추가
  src/main/java/org/devcourse/resumeme/global/advice/ExceptionControllerAdvice.java
Labels: Feat

#96 feat: 프로젝트 조회 api 구현
  src/docs/asciidoc/resume.adoc
  src/main/java/org/devcourse/resumeme/controller/CareerController.java
  src/main/java/org/devcourse/resumeme/controller/ProjectController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ProjectResponse.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/service/ProjectService.java
  src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java
Labels: Feat

#97 feat: 수상 및 자격증 조회 api 구현
  src/docs/asciidoc/resume.adoc
  src/main/java/org/devcourse/resumeme/controller/CertificationController.java
  src/main/java/org/devcourse/resumeme/controller/dto/CertificationCreateRequest.java
  src/main/java/org/devcourse/resumeme/controller/dto/CertificationResponse.java
  src/main/java/org/devcourse/resumeme/domain/resume/Certification.java
  src/test/java/org/devcourse/resumeme/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/domain/resume/CertificationTest.java
Labels: Feat

#100 test: JwtService 테스트
  src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
  src/main/resources/application.yml
  src/test/java/org/devcourse/resumeme/global/auth/token/JwtServiceTest.java
Labels: test

#102 fix: cors 수정
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
  src/main/java/org/devcourse/resumeme/global/config/WebConfig.java
Labels: HotFix

#103 fix: 로컬 주소 추가
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
Labels: HotFix

#98 test: 테스트코드 리팩토링
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
Labels: Refactor

#99 refactor: OAuth2UserInfo 리팩토링
  src/main/java/org/devcourse/resumeme/controller/dto/ResumeCreateRequest.java
  src/main/java/org/devcourse/resumeme/domain/user/BasicInfo.java
  src/main/java/org/devcourse/resumeme/domain/user/Provider.java
  src/main/java/org/devcourse/resumeme/domain/user/User.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2SuccessHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/model/Claims.java
  src/main/java/org/devcourse/resumeme/global/auth/model/UserCommonInfo.java
  src/main/java/org/devcourse/resumeme/repository/UserRepository.java
  src/main/java/org/devcourse/resumeme/service/UserService.java
  src/test/java/org/devcourse/resumeme/domain/resume/ResumeTest.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
Labels: Refactor

#101 feat: 교육사항 조회 api 구현
  src/docs/asciidoc/resume.adoc
  src/main/java/org/devcourse/resumeme/controller/TrainingController.java
  src/main/java/org/devcourse/resumeme/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/domain/resume/DateDetails.java
  src/main/java/org/devcourse/resumeme/domain/resume/EducationalDetails.java
  src/main/java/org/devcourse/resumeme/domain/resume/GPADetails.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/domain/resume/Skill.java
  src/main/java/org/devcourse/resumeme/domain/resume/Training.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/test/java/org/devcourse/resumeme/controller/TrainingControllerTest.java
Labels: Feat

#104 feat: 멘티 정보 조회 response 수정
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/controller/dto/MenteeInfoResponse.java
  src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
Labels: Feat

#105 feat: ExceptionHandlerFilter 추가
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenProvider.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenResolver.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
  src/main/resources/application.yml
  src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
Labels: Feat

#106 fix: sendError -> setStatus, redis 설정 추가
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/resources/application.yml
Labels: HotFix

#107 docs: api 문서 가독성 개선
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/resume.adoc
Labels: Documentation

#108 fix: 토큰 요청 두번 나가는 오류 수정
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
Labels: HotFix

#111 fix: 멘토, 멘티 조회 에러 해결 및 리팩토링
  src/main/java/org/devcourse/resumeme/controller/MenteeController.java
  src/main/java/org/devcourse/resumeme/controller/MentorController.java
  src/main/java/org/devcourse/resumeme/global/advice/ExceptionControllerAdvice.java
  src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
  src/main/java/org/devcourse/resumeme/repository/MenteeRepository.java
  src/main/java/org/devcourse/resumeme/repository/MentorRepository.java
  src/main/java/org/devcourse/resumeme/service/MenteeService.java
  src/main/java/org/devcourse/resumeme/service/MentorService.java
  src/main/java/org/devcourse/resumeme/service/OAuth2InfoRedisService.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
Labels: HotFix

#112 fix: cors 전부 오픈
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
Labels: HotFix

#113 fix: credentials false 변경
  src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
Labels: HotFix

#114 fix: ROLE 고정 문제 수정
  src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
Labels: HotFix

#109 feat: 이력서 직무, 스킬셋, 자기소개 추가
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ResumeInfoRequest.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
Labels: Feat

#116 fix: 403 원인 수정
  src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
Labels: HotFix

#115 test: 테스트 컨테이너 적용
  build.gradle
  src/test/java/org/devcourse/resumeme/common/config/RedisContainerInitializer.java
  src/test/java/org/devcourse/resumeme/common/config/RedisRepositoryConfig.java
  src/test/java/org/devcourse/resumeme/repository/OAuth2InfoRedisRepositoryTest.java
Labels: test

#117 feat: skills, duty 빈값 검증 제거
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: Feat

#118 fix: 테이블 명 수정
  src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: HotFix

#119 feat: 리뷰 반환값 타입 변경
  src/main/java/org/devcourse/resumeme/controller/CommentController.java
  src/test/java/org/devcourse/resumeme/controller/CommentControllerTest.java
Labels: Feat

#120 fix: 시작일 종료일 검증 로직 수정
  src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
Labels: HotFix

#121 feat: duty fetch type 수정
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
Labels: Feat

#122 feat: collectionTable fetch type 수정
  src/main/java/org/devcourse/resumeme/domain/resume/Career.java
  src/main/java/org/devcourse/resumeme/domain/resume/Project.java
  src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java
Labels: Feat

#125 feat: 활동 및 외국어 조회 api 구현
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/controller/ActivityController.java
  src/main/java/org/devcourse/resumeme/controller/ForeignLanguageController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ActivityResponse.java
  src/main/java/org/devcourse/resumeme/controller/dto/ForeignLanguageResponse.java
  src/main/java/org/devcourse/resumeme/domain/resume/Activity.java
  src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java
  src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java
Labels: Feat

#124 docs: api 문서 커스텀
  src/test/java/org/devcourse/resumeme/common/util/ApiDocumentUtils.java
  src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: Documentation

#126 feat: 이력서 제목 저장 api 구현
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/controller/dto/ResumeRequest.java
  src/main/java/org/devcourse/resumeme/domain/resume/Resume.java
  src/main/java/org/devcourse/resumeme/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
Labels: Feat

#128 fix: ConfigurationProperties Scan 베이스 패키지 설정
  src/main/java/org/devcourse/resumeme/global/config/web/WebConfig.java
Labels: HotFix

#129 feat: 이력서 참고링크 api 구현
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/LinkType.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#130 feat: JwtService 로직 및 토큰 헤더 이름 수정
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeController.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeRegisterInfoRequest.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentor/MentorController.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorRegisterInfoRequest.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2FailureHandler.java
  src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java
  src/main/java/org/devcourse/resumeme/global/auth/service/jwt/Token.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
  src/test/java/org/devcourse/resumeme/global/auth/service/jwt/JwtServiceTest.java
Labels: Feat

#131 feat: endpoint 권한 설정 수정
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java
  src/main/resources/application-endpoint.yml
Labels: Feat

#132 docs: RestDocs 최신화
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/docs/asciidoc/reference.adoc
  src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: Documentation

#133 feat: 이벤트 조회 반환 값 추가
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventsResponse.java
  src/main/java/org/devcourse/resumeme/business/event/domain/Event.java
  src/main/java/org/devcourse/resumeme/business/event/domain/EventInfo.java
  src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java
  src/main/java/org/devcourse/resumeme/business/event/repository/EventPositionRepository.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventPositionService.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#134 docs: 제약조건 최신화
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: Documentation

#135 feat: 멘티 이력서 조회 api 구현
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/main/java/org/devcourse/resumeme/common/domain/BaseEntity.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#137 feat: 학점 검증로직 변경
  src/main/java/org/devcourse/resumeme/business/resume/domain/GPADetails.java
Labels: Feat

#138 fix: MenteeToEventRepository 타입 오류 수정
  src/main/java/org/devcourse/resumeme/business/event/repository/MenteeToEventRepository.java
Labels: HotFix

#140 feat: 업무경험 도메인 엔티티 분리
  src/main/java/org/devcourse/resumeme/business/resume/controller/CareerController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/CareerController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/CareerPeriod.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/CareerPeriod.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Duty.java
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/CareerRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/service/CareerService.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/CareerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#139 docs: 이력서 필수값, 제약조건 추가
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
Labels: Documentation

#141 feat: 토큰 설정값 파일 분리
  src/main/java/org/devcourse/resumeme/global/auth/model/jwt/JwtProperties.java
  src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/global/auth/service/jwt/JwtServiceTest.java
Labels: Feat

#142 feat: 외국어, 자격증, 활동 도메인 분리
  src/main/java/org/devcourse/resumeme/business/resume/controller/ActivityController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/CareerController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/certification/CertificationController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/certification/dto/CertificationCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityRequestDto.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageRequestDto.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Certification.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Converter.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ActivityRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/CertificationRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ForeignLanguageRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ActivityService.java
  src/main/java/org/devcourse/resumeme/business/resume/service/CertificationService.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ForeignLanguageService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/ActivityTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/CareerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/CertificationTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/ForeignLanguageTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#143 feat: 교육, 프로젝트 도메인 분리
  src/main/java/org/devcourse/resumeme/business/resume/controller/ProjectController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/TrainingController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/DateDetails.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/EducationalDetails.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/GPADetails.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Project.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Training.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ProjectRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/TrainingRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ProjectService.java
  src/main/java/org/devcourse/resumeme/business/resume/service/TrainingService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/ProjectTest.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/TrainingTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#144 test: 멘토 관련 테스트 코드 추가
  src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
  src/test/java/org/devcourse/resumeme/business/user/domain/mentor/MentorTest.java
  src/test/java/org/devcourse/resumeme/business/user/service/mentor/MentorServiceTest.java
Labels: test

#145 fix: redirect-uri 임시 변경
  src/main/resources/application-auth.yml
Labels: HotFix

#147 fix: dev 환경 redirect-uri 변경
  src/main/resources/application-auth.yml
  src/main/resources/application.yml
Labels: HotFix

#148 fix: 헤더 설정 추가
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java
Labels: HotFix

#149 feat: ComponentCreateRequest 공통화
  src/main/java/org/devcourse/resumeme/business/resume/controller/ActivityController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/certification/dto/CertificationCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityRequestDto.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ComponentCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageRequestDto.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingCreateRequest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
Labels: Feat

#153 feat: component, 리뷰 연관관계 수정
  src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java
  src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentResponse.java
  src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
  src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
  src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/comment/domain/CommentTest.java
Labels: Feat

#152 feat: 멘토 / 멘티 마이페이지 정보 조회
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/user/controller/UserController.java
  src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#154 feat: Postion, Field Enum 값 추가
  src/main/java/org/devcourse/resumeme/common/domain/Field.java
  src/main/java/org/devcourse/resumeme/common/domain/Position.java
  src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/domain/mentee/MenteeTest.java
  src/test/java/org/devcourse/resumeme/common/util/DocumentLinkGenerator.java
Labels: Feat

#155 feat: 이력서 합격률 계산 기능 구현
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java
  src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java
  src/main/java/org/devcourse/resumeme/business/statistics/service/StatisticsService.java
  src/test/java/org/devcourse/resumeme/business/resume/service/StatisticsServiceTest.java
Labels: Feat

#157 feat: ExceptionHandler 토큰 에러 추가
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/devcourse/resumeme/global/exception/TokenException.java
Labels: Feat

#156 feat: 메일 보내기 기능 구현
  build.gradle
  src/main/java/org/devcourse/resumeme/business/mail/EmailInfo.java
  src/main/java/org/devcourse/resumeme/business/mail/EmailType.java
  src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java
  src/main/java/org/devcourse/resumeme/business/mail/service/EmailService.java
  src/main/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationController.java
  src/main/java/org/devcourse/resumeme/global/config/web/AsyncConfig.java
  src/main/resources/application-email.yml
  src/main/resources/application.yml
  src/main/resources/templates/eventOpen.html
  src/main/resources/templates/mentorApproved.html
  src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#160 feat: 어드민 페이지 초안 구현
  build.gradle
  src/main/resources/templates/admin.html
Labels: Feat

#159 feat: 기간별 합격률 계산 기능 구현
  src/main/java/org/devcourse/resumeme/business/resume/domain/PassInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/PassInfoRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java
  src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java
  src/main/java/org/devcourse/resumeme/business/statistics/service/StatisticsService.java
  src/test/java/org/devcourse/resumeme/business/resume/service/StatisticsServiceTest.java
Labels: Feat

#162 fix: 리프레시 토큰 비교 로직 수정 및 로그 추가
  src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java
Labels: HotFix

#163 fix: pathvariable type 수정
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
Labels: HotFix

#164 feat: 통계 어드민 추가
  src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java
  src/main/resources/application-endpoint.yml
Labels: Feat

#161 feat: 로그아웃 기능 구현
  src/docs/asciidoc/all.adoc
  src/main/java/org/devcourse/resumeme/business/user/service/mentee/MenteeService.java
  src/main/java/org/devcourse/resumeme/business/user/service/mentor/MentorService.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandler.java
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java
Labels: Feat

#168 feat: 이력서 삭제
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#167 feat: 이력서 첨삭 완료 기능 구현
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/CompleteEventRequest.java
  src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: Feat

#169 fix: 멘토/멘티 조회 response role 값 수정 및 삭제
  src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/user/domain/Role.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
Labels: Feat

#170 hotfix: 이력서 기본 정보 조회 기능 추가
  src/docs/asciidoc/all.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controllerl/dto/BasicResumeInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: HotFix

#171 fix: 이력서 존재 여부 검증
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
Labels: HotFix

#172 feat: Exception Snippet 추가 및 endpoint 수정
  src/docs/asciidoc/all.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/resources/org/springframework/restdocs/templates/exception-response.snippet
Labels: Feat

#173 fix: response role 값 수정 및 id 필드 추가
  src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
  src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java
Labels: HotFix

#174 fix: 엔드포인트 권한 추가
  src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: HotFix

#176 fix: 이력서 생성 엔드포인트 수정
  src/main/resources/application-endpoint.yml
Labels: HotFix

#177 feat: 리뷰 조회 반환값 수정
  src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java
  src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentResponse.java
  src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
  src/main/java/org/devcourse/resumeme/common/domain/BaseEntity.java
  src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/comment/domain/CommentTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
Labels: Feat

#178 hotfix: 반환 id 변경
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
Labels: HotFix

#179 fix: 영속성 컴포넌트 수정
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
Labels: HotFix

#175 fix: optional 값 검증 로직 수정 및 update 권한 검증 추가
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeController.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeInfoUpdateRequest.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeRegisterInfoRequest.java
  src/main/java/org/devcourse/resumeme/business/user/controller/mentor/MentorController.java
  src/main/java/org/devcourse/resumeme/business/user/repository/mentee/MenteeRepository.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
  src/main/resources/application-endpoint.yml
Labels: HotFix

#180 fix: 반환 타입 수정
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
Labels: HotFix

#181 feat: 멘토 마이페이지 이벤트 조회
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: Feat

#182 feat: 첨삭 수정 삭제 기능 구현
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java
  src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentUpdateRequest.java
  src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java
  src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
Labels: Feat

#183 fix: 멘티 로그아웃 성공시 return 추가
  src/main/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandler.java
Labels: HotFix

#186 fix: component 전체 조회 type null 수정
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
Labels: HotFix

#184 docs: component, event api doc 예외코드 추가
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
Labels: Documentation

#185 feat: 외부 링크 component 분리
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ComponentCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/LinkControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#187 test: component test코드 통합
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentRequest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/LinkControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
Labels: test

#189 feat: 블럭 전체 조회 수정
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
Labels: Feat

#190 test: JWT Token Filter Test 작성
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/FilterTestController.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilterTest.java
Labels: test

#188 feat: 이벤트 전체 조회 api 통합
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: Feat

#191 fix: 이력서 삭제 권한 엔드포인트 수정
  src/main/resources/application-endpoint.yml
Labels: HotFix

#192 fix: skills 타입 변환
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java
Labels: HotFix

#193 fix: resumeInfo 생성자 추가
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
Labels: HotFix

#194 fix: resumeInfo getter 수정
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
Labels: HotFix

#196 fix: 지연 초기화 에러 수정
  src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
Labels: HotFix

#197 docs: 활동사항 조회 docs 추가
  src/docs/asciidoc/all.adoc
Labels: Documentation

#198 fix: 삭제 엔드포인트 권한 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#199 fix: 조회 엔드포인트 권한 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#200 fix: isTeam 조건문 변경
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
Labels: HotFix

#202 fix: 에러 수정
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingCreateRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/GPADetails.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java
  src/test/java/org/devcourse/resumeme/business/resume/domain/ActivityTest.java
Labels: HotFix

#201 fix: 필터 순서 변경
  src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
Labels: HotFix

#204 fix: 테스트 수정, dto 필드 추가
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeResponse.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: HotFix

#205 fix: 이력서 기본조회 수정 엔드포인트 변경
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: HotFix

#203 feat: 생성 시간 기준 정렬
  src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
Labels: Feat

#206 fix: 401 에러 추가
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
  src/main/java/org/devcourse/resumeme/global/exception/UnAuthenticatedException.java
Labels: HotFix

#213 fix: endpoint 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#216 fix: id 순서 변경
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
Labels: HotFix

#212 feat: Component 복사 기능 추가
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
  src/test/java/org/devcourse/resumeme/business/resume/repository/CustomComponentRepositoryTest.java
Labels: Feat

#211 feat: 멘티 첨삭 리스트 조회
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/java/org/devcourse/resumeme/business/event/service/vo/AllEventFilter.java
  src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java
  src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java
  src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Feat

#207 feat: 멘토 승인 페이지 구현
  src/main/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationController.java
  src/main/resources/templates/mentorApprovalPage.html
  src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java
Labels: Feat

#217 hotfix: 멘토 개인정보 업데이트 request 필드 수정
  src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoUpdateRequest.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentee/RequiredInfo.java
  src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
  src/main/resources/application-endpoint.yml
  src/main/resources/application-jwt.yml
  src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
Labels: HotFix

#218 feat: 이력서, Component 반환 값 추가
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#219 feat: 스케줄링을 통한 이벤트 진행 상태 값 변경
  src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/java/org/devcourse/resumeme/global/config/web/WebConfig.java
Labels: Feat

#220 fix: 마이페이지 이벤트 조회 엔드포인트 및 권한 확인 로직 추가
  src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java
  src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
Labels: HotFix

#222 docs: readme 파일 수정
  README.md
Labels: Documentation

#223 fix: 멘티 정보 수정 엔드포인트 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#224 refactor: Component 도메인 리팩토링
  src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Certification.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Converter.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ForeignLanguage.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Project.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Property.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Training.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Duty.java
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
Labels: Refactor

#225 fix: rest docs 누락 추가
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/docs/asciidoc/mentor.adoc
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
Labels: Documentation, HotFix

#226 fix: 멘티 정보 수정 엔드포인트 수정
  src/main/resources/application-endpoint.yml
Labels: HotFix

#227 feat: 이력서 메모 작성, 조회 기능 구현
  src/docs/asciidoc/all.adoc
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeMemoRequest.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeMemoResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: Feat

#228 feat: 이벤트 전체 조회 페이징 추가
  src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventPageResponse.java
  src/main/java/org/devcourse/resumeme/business/event/domain/EventPosition.java
  src/main/java/org/devcourse/resumeme/business/event/repository/EventPositionRepository.java
  src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventPositionService.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/java/org/devcourse/resumeme/global/auth/service/authorization/AuthorizationResolver.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/business/event/service/EventPositionServiceTest.java
  src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
Labels: Feat

#229 test: CustomLogoutHandler 테스트 추가
  src/docs/asciidoc/all.adoc
  src/main/resources/application-endpoint.yml
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
  src/test/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandlerTest.java
Labels: test

#231 fix: resume service 수정
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
Labels: HotFix

#230 fix: entityGraph 수정
  src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
Labels: HotFix

#232 fix: 엔드포인트 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#233 fix: 멘토 엔드포인트 추가
  src/main/resources/application-endpoint.yml
Labels: HotFix

#234 fix: Map value null값 fallback 구축
  src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/LocalDateUtils.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Project.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Training.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/main/resources/application.yml
Labels: HotFix

#236 멘토 아이디 추가, duty 빈배열 추가
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventInfoResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
  src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
Labels: HotFix

#237 fix: 엔드포인트 수정 및 자료구조 변경
  src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java
  src/main/java/org/devcourse/resumeme/global/exception/advice/ExceptionControllerAdvice.java
  src/main/resources/application-endpoint.yml
Labels: HotFix

#235 feat: 이력서 pdf 생성 기능 구현
  build.gradle
  src/main/java/org/devcourse/resumeme/business/pdf/controller/PDFController.java
  src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java
  src/main/resources/application-endpoint.yml
Labels: Feat

#238 chore: pdf 엔드포인트 수정
  src/main/resources/application-endpoint.yml
Labels: HotFix

#239 fix: 엔드포인트 변경
  src/main/resources/application-endpoint.yml
Labels: HotFix

#241 fix: chromedriver 경로 수정 및 PDFGenerator 리팩토링
  src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java
Labels: HotFix

#245 fix: jpql 실행 추가
  src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java
Labels: HotFix

#247 fix: duties null 체크 추가
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java
Labels: HotFix

#246 fix: component copy 로직 변경
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
Labels: HotFix

#248 fix: duty component 변환 수정
  src/main/java/org/devcourse/resumeme/business/resume/domain/career/Duty.java
Labels: HotFix

#249 fix: 이력서 컴포넌트 복사 로직 수정
  src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
Labels: HotFix

#242 feat: 이력서 원본 데이터 스냅샷 기능
  src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java
  src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/SnapshotController.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
  src/main/java/org/devcourse/resumeme/business/resume/entity/Snapshot.java
  src/main/java/org/devcourse/resumeme/business/resume/repository/SnapshotRepository.java
  src/main/java/org/devcourse/resumeme/business/resume/service/SnapshotService.java
  src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
Labels: Feat

#251 refactor: EventController 수정 V2 생성
  src/main/java/org/devcourse/resumeme/business/event/controller/EventControllerV2.java
  src/main/java/org/devcourse/resumeme/business/event/controller/dto/v2/EventUpdateRequest.java
  src/main/java/org/devcourse/resumeme/business/event/domain/Event.java
  src/main/java/org/devcourse/resumeme/business/event/domain/vo/EventComplete.java
  src/main/java/org/devcourse/resumeme/business/event/domain/vo/EventReject.java
  src/main/java/org/devcourse/resumeme/business/event/domain/vo/EventUpdateModel.java
  src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
  src/main/java/org/devcourse/resumeme/business/event/service/vo/EventCompleteV2.java
  src/main/java/org/devcourse/resumeme/business/event/service/vo/EventRejectV2.java
  src/main/java/org/devcourse/resumeme/business/event/service/vo/EventUpdateVo.java
  src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerV2Test.java
  src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
Labels: Refactor

#253 fix: 이벤트, 이력서 조회 조건 추가
  src/docs/asciidoc/mentee.adoc
  src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java
  src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
  src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
  src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java
  src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
Labels: HotFix
